# Generated by Django 3.0.8 on 2020-12-22 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Login',
            new_name='User',
        ),
    ]
