# Generated by Django 3.0.8 on 2020-12-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20201222_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField(max_length=20)),
                ('name', models.TextField()),
                ('isadmin', models.BooleanField()),
                ('offid', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
