# Generated by Django 3.0.8 on 2020-12-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20201222_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.TextField(max_length=20)),
                ('name', models.TextField()),
                ('isadmin', models.BooleanField()),
                ('offid', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='User_Details',
        ),
    ]
