# Generated by Django 3.0.8 on 2020-12-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20201225_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ecopy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
