# Generated by Django 3.0.8 on 2020-12-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20201225_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='coverpic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.TextField(),
        ),
    ]
