# Generated by Django 3.0.8 on 2020-12-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20201226_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isavail',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='lended_by',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='reversed_by',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
