# Generated by Django 3.0.8 on 2020-12-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_auto_20201227_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ldate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='rdate',
            field=models.DateField(null=True),
        ),
    ]
